// File generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
// This creates your firebase_options.dart with real values from your Firebase project.
//
// If you haven't set up Firebase yet:
// 1. Go to https://console.firebase.google.com/
// 2. Create a project (or use existing)
// 3. Run: flutterfire configure
// 4. Select platforms (Android, Web for Windows)
//
// Until you run `flutterfire configure`, this file has placeholders.
// The app will run using local auth fallback.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:xxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'aqi-buddy-project',
    authDomain: 'aqi-buddy-project.firebaseapp.com',
    storageBucket: 'aqi-buddy-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:xxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'aqi-buddy-project',
    storageBucket: 'aqi-buddy-project.appspot.com',
  );
}
